//
// AWSConfiguration.h
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.6
//
#import <AWSCore/AWSCore.h>
#import <AWSCognito/AWSCognito.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:219b0a26-6db6-4f5c-bb72-c13c5d883342"
// AMAZON MOBILE ANALYTICS
#define AMAZON_MOBILE_ANALYTICS_APP_ID @"4fae82f28fa34e66a5717ab55dd5443f"
// CONTENT DELIVERY
#define AWS_CONTENT_MANAGER_S3_BUCKET_NAME @"cmv-contentdelivery-mobilehub-1695406899"
#define AWS_CONTENT_MANAGER_CLOUD_FRONT_DOMAIN @"dmgpccwajo2md.cloudfront.net"
#define AWS_CONTENT_MANAGER_CLOUD_FRONT_ORIGIN_S3 @"cmv-contentdelivery-mobilehub-1695406899"
// USER FILES
#define AWS_USER_FILE_MANAGER_S3_BUCKET_NAME @"cmv-userfiles-mobilehub-1695406899"
// USER AGENT
#define AWS_MOBILEHUB_USER_AGENT @"MobileHub 0f9150b3-d40c-45ba-8449-17818938352b aws-my-sample-app-ios-objc-v0.6"
// PUSH
#define AWS_SNS_PLATFORM_APPLICATION_ARN @"arn:aws:sns:us-east-1:286534156638:app/APNS/cmv_MOBILEHUB_1695406899"
#define AWS_SNS_ALL_DEVICE_TOPIC_ARN @"arn:aws:sns:us-east-1:286534156638:cmv_alldevices_MOBILEHUB_1695406899"
#define S3BucketName @"cmv-events"
